environment:
  CIBW_BEFORE_BUILD: .appveyor/build-libsrtp.bat
  CIBW_SKIP: cp27-* cp33-* cp34-*
  CIBW_TEST_COMMAND: python -m unittest pylibsrtp.tests
  CL: /I%TEMP%\libsrtp.install\include
  LINK: /LIBPATH:%TEMP%\libsrtp.install\lib
install:
  - cmd: C:\Python36-x64\python.exe -m pip install cibuildwheel
build_script:
  - cmd: C:\Python36-x64\python.exe -m cibuildwheel --output-dir wheelhouse
