addons:
  apt:
    packages:
    - libsrtp2
after_success: coveralls
dist: trusty
install: pip install cffi coveralls flake8
language: python
python:
  - 3.5
  - 3.6
script:
  - flake8 pylibsrtp tests.py
