after_success: coveralls
dist: trusty
install: pip install cffi coveralls flake8
language: python
python:
  - 3.5
  - 3.6
script:
  - .travis/build-libsrtp
  - export LD_LIBRARY_PATH=$PWD/libsrtp:$LD_LIBRARY_PATH
  - flake8 pylibsrtp tests.py
  - coverage run setup.py test
