after_success: coveralls
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew install python3
      python3 -m venv env
      source env/bin/activate
    fi
  - pip install cffi coveralls flake8
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
script:
  - .travis/build-libsrtp
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      export DYLD_LIBRARY_PATH=$PWD/libsrtp:$DYLD_LIBRARY_PATH
    else
      export LD_LIBRARY_PATH=$PWD/libsrtp:$LD_LIBRARY_PATH
    fi
  - flake8 pylibsrtp tests.py
  - coverage run setup.py test
