after_success: coveralls
dist: trusty
install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
      brew update
      brew upgrade python3
      brew install srtp
      python3 -m venv env
      source env/bin/activate
    else
      .travis/build-libsrtp
      export CFLAGS=-I$PWD/libsrtp/local/include
      export LDFLAGS=-L$PWD/libsrtp/local/lib
    fi
  - pip install coveralls flake8
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "pypy3"
script:
  - flake8 pylibsrtp tests.py
  - coverage run setup.py test
