dist: trusty
env:
  global:
    - CIBW_BEFORE_BUILD=".travis/build-libsrtp"
    - CIBW_ENVIRONMENT="CFLAGS=-I/tmp/libsrtp/include LDFLAGS=-L/tmp/libsrtp/lib"
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - CIBW_TEST_COMMAND="python3 -m unittest pylibsrtp.tests"
install: source .travis/install
language: python
matrix:
  include:
  - env: BUILD=lint
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "3.8"
    dist: xenial
    sudo: true
  - python: "pypy3"
  - env: BUILD=sdist
    python: "3.6"
  - env: BUILD=wheel
    python: "3.6"
    services: docker
  - env: BUILD=wheel
    os: osx
    language: generic
script: .travis/script
