after_success: coveralls
dist: trusty
env:
  global:
    - CIBW_BEFORE_BUILD=.travis/build-libsrtp
    - CIBW_ENVIRONMENT="CFLAGS=-I/tmp/libsrtp/include LDFLAGS=-L/tmp/libsrtp/lib"
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - CIBW_TEST_COMMAND="python3 -m unittest pylibsrtp.tests"
install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew upgrade python3
    fi
    if [ "$BUILD" = "wheel" ]; then
      pip3 install cibuildwheel
    else
      .travis/build-libsrtp
      export CFLAGS=-I/tmp/libsrtp/include
      export LDFLAGS=-L/tmp/libsrtp/lib
      pip3 install coveralls flake8
    fi
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "pypy3"
  - env: BUILD=wheel
    python: "3.6"
    services: docker
  - env: BUILD=wheel
    os: osx
    language: generic
script:
  - |
    if [ "$BUILD" = "wheel" ]; then
      cibuildwheel --output-dir wheelhouse
      if [ -n "$TRAVIS_TAG" ]; then
        pip3 install twine
        python3 -m twine upload --skip-existing wheelhouse/*
      fi
    else
      flake8 pylibsrtp
      coverage run setup.py test
    fi
