name: tests

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install packages
        run: pip install black flake8 isort
      - name: Run linters
        run: |
          flake8 src tests
          isort -c -df -rc src tests
          black --check --diff src tests

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.8, 3.7, 3.6, pypy3]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install OS Packages
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install srtp
      - name: Install OS Packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsrtp2-dev
      - name: Run tests
        run: |
          pip install -U pip setuptools wheel
          pip install coverage
          pip install .
          coverage run -m unittest discover -v
          coverage xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        if: matrix.python != 'pypy3'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
